### PR TITLE
Bug Fix: Verify album levels range check incorrect

### PR DESCRIPTION
**Pull request by rock-meister**
Verify album levels range is failing.  This is my first pull request.  Apologies if this is not the correct way to do a PR.

### CODE REVIEW

**Comment by Salvoxia** [comment]
Thank you! Seems like something slipped through during refactoring..
I'll verify your fix and merge at later today.
FYI: There are no functional changes between the current `latest` tag and the `0.15.0` release. Using `0.15.0` tag is a workaround until the PR is merged.

**Review by Salvoxia — CHANGES_REQUESTED** [review]
I don't think you meant this to be included in this same pull request. It should only contain the bugfix.

**Comment by rock-meister** [comment]
> I don't think you meant this to be included in this same pull request. It should only contain the bugfix.

It is my misunderstanding.  I wanted to create the PR only for the bugfix.  I don't understand why my 2nd commit is coming through.

**Comment by Salvoxia** [comment]
The pull request targets the complete branch you created it for - so the `main` branch of your fork from the time on you created the pull request. It will contain everything you commit on that branch until the pull request is closed.
You'll have to rollback that one commit and either stash it somewhere until the PR is closed, or create another branch on your fork to merge back into your main.

**Comment by rock-meister** [comment]
That explains it.  I have done the following to revert the last commit out.  Let me know if this works. 
```
git reset HEAD^ # remove commit locally
git push origin +HEAD # force-push the new HEAD commit
```

**Review by Salvoxia — APPROVED** [review]

**Pull request merged**
